name: Go package

on:
  push:
    tags:
      - v*

env:
  GO_VERSION: 1.20

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Package
        run: make package
      - name: Upload Release Distribution
        uses: actions/upload-artifact@v3
        with:
          name: Distribution Package
          path: dist/flightvisualizer.zip
