name: Go package

on:
  push:
    branches:
      - main
      - mock-output-folder

env:
  GO_VERSION: '1.20'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Install dependencies
        run: go get .
      - name: Test with Go
        run: go test ./...
      - name: Super Lint
        uses: docker://github/super-linter:v3
        env:
          # TODO change VALIDATE_ALL_CODEBASE to false once we've established a baseline
          VALIDATE_ALL_CODEBASE: true
          # TODO change to main; WHY IS THIS HERE ANYWAYS????
          DEFAULT_BRANCH: mock-output-folder
